/** \file
 *  This C++ header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : Grammar/MorphDSL.g
 *     -                            On : 2015-06-30 11:48:23
 *     -                for the parser : MorphDSLParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C++ language generator and runtime by Gokulakannan Somasundaram ( heavy lifting from C Run-time by Jim Idle )
 *
 *
 * The parser 
MorphDSLParser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Gokulakannan Somasundaram. 
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_MorphDSLParser_H
#define _MorphDSLParser_H
/* =============================================================================
 * Standard antlr3 C++ runtime definitions
 */
#include    <antlr3.hpp>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */


#include "MorphDSLLexer.hpp"
#include "Razredi/Enums.h"
#include "Razredi/SqlWhere.h"

namespace LPM_MorphDSL {
	class MorphDSLSemantics;
	class Identifier;
}



using namespace std;

#ifdef	WIN32
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/* ========================
 * BACKTRACKING IS ENABLED
 * ========================
 */

	namespace 	LPM_MorphDSL  {


typedef MorphDSLParserTraits MorphDSLParserImplTraits;

 struct synpred56_MorphDSL {}; 
 struct synpred57_MorphDSL {}; 

struct MorphDSLParser_figurevector_return : public MorphDSLParserImplTraits::RuleReturnValueType
{
public:
	typedef MorphDSLParserImplTraits::RuleReturnValueType BaseType;

    
    MorphDSLParser_figurevector_return()
    {
    }

    MorphDSLParser_figurevector_return( BaseParserType* parser )
        : BaseType(parser)
    {
    }

    MorphDSLParser_figurevector_return( const MorphDSLParser_figurevector_return& n )
    : BaseType(n)
    {
    }

    MorphDSLParser_figurevector_return&
    operator=( const MorphDSLParser_figurevector_return& n )
    {
    	BaseType::operator=( n );
    	return *this;
    }

};





struct MorphDSLParser_operatorSql_return : public MorphDSLParserImplTraits::RuleReturnValueType
{
public:
	typedef MorphDSLParserImplTraits::RuleReturnValueType BaseType;
    SelectKw::Keyword selectKw;
    std::string funkcija;

    
    MorphDSLParser_operatorSql_return()
    {
    }

    MorphDSLParser_operatorSql_return( BaseParserType* parser )
        : BaseType(parser)
    {
    }

    MorphDSLParser_operatorSql_return( const MorphDSLParser_operatorSql_return& n )
    : BaseType(n)
    , selectKw(n.selectKw) ,funkcija(n.funkcija) 
    {
    }

    MorphDSLParser_operatorSql_return&
    operator=( const MorphDSLParser_operatorSql_return& n )
    {
    	BaseType::operator=( n );
    	selectKw = n.selectKw; 
    	funkcija = n.funkcija; 
    	return *this;
    }

};





struct MorphDSLParser_operatorName_return : public MorphDSLParserImplTraits::RuleReturnValueType
{
public:
	typedef MorphDSLParserImplTraits::RuleReturnValueType BaseType;

    
    MorphDSLParser_operatorName_return()
    {
    }

    MorphDSLParser_operatorName_return( BaseParserType* parser )
        : BaseType(parser)
    {
    }

    MorphDSLParser_operatorName_return( const MorphDSLParser_operatorName_return& n )
    : BaseType(n)
    {
    }

    MorphDSLParser_operatorName_return&
    operator=( const MorphDSLParser_operatorName_return& n )
    {
    	BaseType::operator=( n );
    	return *this;
    }

};





struct MorphDSLParser_sqlWhere_return : public MorphDSLParserImplTraits::RuleReturnValueType
{
public:
	typedef MorphDSLParserImplTraits::RuleReturnValueType BaseType;
    std::string keyword;
    SqlWhere* stavek;

    
    MorphDSLParser_sqlWhere_return()
    {
    }

    MorphDSLParser_sqlWhere_return( BaseParserType* parser )
        : BaseType(parser)
    {
    }

    MorphDSLParser_sqlWhere_return( const MorphDSLParser_sqlWhere_return& n )
    : BaseType(n)
    , keyword(n.keyword) ,stavek(n.stavek) 
    {
    }

    MorphDSLParser_sqlWhere_return&
    operator=( const MorphDSLParser_sqlWhere_return& n )
    {
    	BaseType::operator=( n );
    	keyword = n.keyword; 
    	stavek = n.stavek; 
    	return *this;
    }

};





struct MorphDSLParser_sqlWhereKeyword_return : public MorphDSLParserImplTraits::RuleReturnValueType
{
public:
	typedef MorphDSLParserImplTraits::RuleReturnValueType BaseType;

    
    MorphDSLParser_sqlWhereKeyword_return()
    {
    }

    MorphDSLParser_sqlWhereKeyword_return( BaseParserType* parser )
        : BaseType(parser)
    {
    }

    MorphDSLParser_sqlWhereKeyword_return( const MorphDSLParser_sqlWhereKeyword_return& n )
    : BaseType(n)
    {
    }

    MorphDSLParser_sqlWhereKeyword_return&
    operator=( const MorphDSLParser_sqlWhereKeyword_return& n )
    {
    	BaseType::operator=( n );
    	return *this;
    }

};





struct MorphDSLParser_interval_return : public MorphDSLParserImplTraits::RuleReturnValueType
{
public:
	typedef MorphDSLParserImplTraits::RuleReturnValueType BaseType;
    double start;
    double stop;

    
    MorphDSLParser_interval_return()
    {
    }

    MorphDSLParser_interval_return( BaseParserType* parser )
        : BaseType(parser)
    {
    }

    MorphDSLParser_interval_return( const MorphDSLParser_interval_return& n )
    : BaseType(n)
    , start(n.start) ,stop(n.stop) 
    {
    }

    MorphDSLParser_interval_return&
    operator=( const MorphDSLParser_interval_return& n )
    {
    	BaseType::operator=( n );
    	start = n.start; 
    	stop = n.stop; 
    	return *this;
    }

};





struct MorphDSLParser_vector_return : public MorphDSLParserImplTraits::RuleReturnValueType
{
public:
	typedef MorphDSLParserImplTraits::RuleReturnValueType BaseType;

    
    MorphDSLParser_vector_return()
    {
    }

    MorphDSLParser_vector_return( BaseParserType* parser )
        : BaseType(parser)
    {
    }

    MorphDSLParser_vector_return( const MorphDSLParser_vector_return& n )
    : BaseType(n)
    {
    }

    MorphDSLParser_vector_return&
    operator=( const MorphDSLParser_vector_return& n )
    {
    	BaseType::operator=( n );
    	return *this;
    }

};





class MorphDSLParserTokens
{
public:
	/** Symbolic definitions of all the tokens that the 
parser
 will work with.
	 * \{
	 *
	 * Antlr will define EOF, but we can't use that as it it is too common in
	 * in C header files and that would be confusing. There is no way to filter this out at the moment
	 * so we just undef it here for now. That isn't the value we get back from C recognizers
	 * anyway. We are looking for ANTLR_TOKEN_EOF.
	 */
	enum Tokens 
	{
		EOF_TOKEN = MorphDSLParserImplTraits::CommonTokenType::TOKEN_EOF
		, T__72 = 72 
		, COMMENT = 4 
		, DOUBLENUMBER = 5 
		, ESC_SEQ = 6 
		, HEX_DIGIT = 7 
		, ID = 8 
		, NUMBER = 9 
		, OCTAL_ESC = 10 
		, STRING = 11 
		, T_AND = 12 
		, T_AREA = 13 
		, T_AREA_SQL = 14 
		, T_ATRIBUTE = 15 
		, T_ATTRIBUTE = 16 
		, T_ATTRIBUTE_SQL = 17 
		, T_BOUNDARY = 18 
		, T_BOX = 19 
		, T_CLOSE = 20 
		, T_COMMA = 21 
		, T_COMPLEMENT = 22 
		, T_CROP = 23 
		, T_DAP = 24 
		, T_DIFERENTIALPROFILES = 25 
		, T_DILATE = 26 
		, T_DISTANCETRANSFORM = 27 
		, T_DMP = 28 
		, T_DOUBLE_QUOTE = 29 
		, T_EQUALS = 30 
		, T_ERODE = 31 
		, T_EXTERNAL = 32 
		, T_EXTERNAL_GRADIENT = 33 
		, T_FROM = 34 
		, T_GRADIENT = 35 
		, T_HITMISS = 36 
		, T_INTERNAL = 37 
		, T_INTERNAL_GRADIENT = 38 
		, T_INTERSECTION = 39 
		, T_LESS_THAN = 40 
		, T_LESS_THAN_OR_EQ = 41 
		, T_LOAD = 42 
		, T_LPAREN = 43 
		, T_MAPPING = 44 
		, T_MASK = 45 
		, T_MORE_THAN = 46 
		, T_MORE_THAN_OR_EQ = 47 
		, T_MORPHOLOGICAL = 48 
		, T_MSLS = 49 
		, T_MULTIPLY = 50 
		, T_NEGATE = 51 
		, T_NORMALIZE = 52 
		, T_NOT_EQUAL = 53 
		, T_OKROGLOST = 54 
		, T_OPEN = 55 
		, T_RECONSTRUCTION = 56 
		, T_RESPONSE = 57 
		, T_RPAREN = 58 
		, T_SEGMENTATION = 59 
		, T_SELECT = 60 
		, T_SET = 61 
		, T_STAR = 62 
		, T_SUBTRACT = 63 
		, T_TRESHOLD = 64 
		, T_UNION = 65 
		, T_VOLUMENT = 66 
		, T_WATHERSHADE = 67 
		, T_WHERE = 68 
		, T_WITHOUT = 69 
		, UNICODE_ESC = 70 
		, WS = 71 
	};

};

/** Context tracking structure for 
MorphDSLParser

 */
class MorphDSLParser : public 
MorphDSLParserImplTraits::BaseParserType
, public MorphDSLParserTokens
{
public:
	typedef MorphDSLParserImplTraits ImplTraits;
	typedef MorphDSLParser ComponentType;
	typedef ComponentType::StreamType StreamType;
	typedef 
MorphDSLParserImplTraits::BaseParserType
 BaseType;
	typedef ImplTraits::RecognizerSharedStateType<StreamType> RecognizerSharedStateType;
	typedef StreamType InputType;
	static const bool IsFiltered = false;


private:	
public:
    MorphDSLParser(InputType* instream);
    MorphDSLParser(InputType* instream, RecognizerSharedStateType* state);

    void init(InputType* instream  );

     
     void
     program (); 
     
     void
     load (); 
     
     void
     assignment (); 
     
     MorphDSLParser_figurevector_return
     figurevector (); 
     
     Identifier*
     var (); 
     
     SubId::SubIdentifier
     subId (); 
     
     Sql*
     sql (std::string spremenljivka); 
     
     MorphDSLParser_operatorSql_return
     operatorSql (); 
     
     SelectKw::Keyword
     selectKeyword (); 
     
     MorphDSLParser_operatorName_return
     operatorName (); 
     
     MorphDSLParser_sqlWhere_return
     sqlWhere (); 
     
     MorphDSLParser_sqlWhereKeyword_return
     sqlWhereKeyword (); 
     
     RelOp::RelacijskiOperatorji
     relOp (); 
     
     void
     operatorsBB (); 
     
     void
     operatorsGG (); 
     
     MorphDSLParser_interval_return
     interval (); 
     
     void
     operatorsBBGG (); 
     
     void
     operatorsBOX (); 
     
     void
     operatorsRECONSTRUCTION (); 
     
     void
     operatorsAREA (); 
     
     void
     operatorsATTRIBUTE (); 
     
     void
     operatorsBG (); 
     
     void
     operatorsGB (); 
     
     void
     marker (); 
     
     MorphDSLParser_vector_return
     vector (); 


      
     bool
     msynpred( antlr3::ClassForwarder< synpred56_MorphDSL > );
        void msynpred56_MorphDSL_fragment ();
      
     bool
     msynpred( antlr3::ClassForwarder< synpred57_MorphDSL > );
        void msynpred57_MorphDSL_fragment ();
    // Delegated rules

    const char *    getGrammarFileName();
    void            reset();
    ~MorphDSLParser();



    private:
    	MorphDSLSemantics* s;

        int MorphDSLParser::toInt(const CommonTokenType* token) {
            int number;
            istringstream(token->getText()) >> number;

            return number;
        }

        double MorphDSLParser::toDouble(const CommonTokenType* token) {
            double number;
            istringstream(token->getText()) >> number;

            return number;
        }

};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//

/* End of token definitions for MorphDSLParser
 * =============================================================================
 */
/** } */

	}


#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
